[package]
name = "rayt"
version = "0.1.1"
authors = ["Bright Hong <brighthong233@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7.3"
rayon = "1.0.0"
itertools = "0.8.0"
image = "0.23"

[dev-dependencies]
float-cmp = "0.8.0"
